version: '3.0'
services:
    php:
        build: .
        ports:
            - "80:80"
        volumes:
            - /home/matheus/Área de Trabalho/Projeto/Projeto-sistemaCadastro:/var/www/html
        networks:
            - backend
    mysql:
        image: mariadb
        container_name: database
        expose:
            - 3306
        ports:
            - "3306:3306"
        networks:
            - backend
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=api
            - MYSQL_PASSWORD=secret
            - MYSQL_DATABASE=sistema_cadastro
    postgres:
        image: postgres
        container_name: databasePostgres
        expose:
            - 5432
        ports:
            - "5432:5432"
        networks:
            - backend
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=sistema_cadastro
networks:
    backend: